### PR TITLE
Update Date.NumDaysInMonth.fmfn

### PR DESCRIPTION
**Pull request by DanShockley**
bug-fix (prev code was off-by-one)
I was looking through your extensive set of custom functions, and noticed that this would return an answer that was lower by 1 than the actual number of days in a month. Here's code to correct that.

### CODE REVIEW

**Comment by DanShockley** [comment]
I also added an isNumeric function, along with a couple fixes in DataType.

**Comment by DanShockley** [comment]
Hope you find these changes useful.

**Comment by aulbricht** [comment]
Thanks for the contributions, Dan! I'll review when I get a chance.

**Review by aulbricht — APPROVED** [review]
good catch!

**Pull request merged**
